// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package handler

import (
	"github.com/google/wire"
	"ipfs-file-api/internal/file/service"
)

// Injectors from wire.go:

func InitialFileCIDHandler() *FileCIDHandler {
	fileCIDService := service.InitialFileCIDService()
	fileCIDHandler := NewFileCIDHandler(fileCIDService)
	return fileCIDHandler
}

// wire.go:

var (
	FileCIDHandlerSet = wire.NewSet(NewFileCIDHandler, service.InitialFileCIDService)
)
