// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

import (
	"github.com/google/wire"
	"ipfs-file-api/internal/file/entity"
	"ipfs-file-api/internal/file/repository"
)

// Injectors from wire.go:

func InitialFileCIDService() entity.FileCIDService {
	fileCIDRepository := repository.InitialFileCIDRepository()
	entityFileCIDService := NewFileCIDService(fileCIDRepository)
	return entityFileCIDService
}

// wire.go:

var (
	FileCIDServiceSet = wire.NewSet(NewFileCIDService, repository.InitialFileCIDRepository)
)
